name: Run tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 18-ea ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu'

      - name: Build, test, and generate reports
        run: mvn clean install test surefire-report:report

      - name: Set up Docker Buildx
        if: ${{ github.event_name == 'push' }}
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_API_KEY }}

      - name: Build and push Producer
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v4
        with:
          context: ./producer
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/producer:latest

      - name: Build and push Consumer
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v4
        with:
          context: ./consumer
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/consumer:latest