name: Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 18-ea ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu'

      - name: Build, test, and generate reports
        run: mvn clean install test surefire-report:report

      - name: Build and Publish Docker Images
        run: |
          export DOCKER_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}
            
          # Build Producer Docker Image
          docker build -t $DOCKER_USERNAME/producer:last .
          
          # Build Consumer Docker Image
          docker build -t $DOCKER_USERNAME/consumer:last .
          
          # Login in Docker Hub
          echo ${{ secrets.DOCKER_HUB_API_KEY }} | docker login -u DOCKER_USERNAME --password-stdin
          
          # Publish Producer Docker Image
          docker push $DOCKER_USERNAME/producer:last
            
          # Publish Consumer Docker Image
          docker push $DOCKER_USERNAME/consumer:last
